// Auto-generated by LibreLane
module clb_3bit(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input[2:0] clb_in,
  input[7:0] lut_data_in,
  input clb_clk_in,
  input clb_mode_seq,
  output clb_out
);
endmodule
